// proto2mysql 自带的建表选项定义。
//
// 用法：在你的 .proto 里 import 本文件，然后在 message / field 上声明表配置，
// 运行时 RegisterTable 会自动读取，无需在 Go 代码里传 TableOption：
//
//	import "proto2mysql_option.proto";
//
//	option (proto2mysql.db) = true;   // 文件级标识：本文件用于 proto2mysql 建表
//
//	message user {
//	  option (proto2mysql.table_name)         = "user";
//	  option (proto2mysql.primary_key)        = "id";           // 逗号分隔 = 联合主键
//	  option (proto2mysql.auto_increment_key) = "id";
//	  option (proto2mysql.index)              = "last_login";   // 分号分隔多个索引；索引内逗号分隔 = 联合索引
//	  option (proto2mysql.unique_key)         = "email";        // 逗号分隔 = 联合唯一键
//
//	  uint64 id = 1;
//	  string email = 2 [(proto2mysql.max_length) = 255];        // 主键/唯一键里的 string/bytes 列宽（默认 191）
//	  string display_name = 3 [(proto2mysql.nullable) = true];  // 该列允许为 NULL
//	  uint64 last_login = 4;
//	}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto2mysql_option.proto

package pbopt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_proto2mysql_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         500000,
		Name:          "proto2mysql.db",
		Tag:           "varint,500000,opt,name=db",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500001,
		Name:          "proto2mysql.table_name",
		Tag:           "bytes,500001,opt,name=table_name",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500002,
		Name:          "proto2mysql.primary_key",
		Tag:           "bytes,500002,opt,name=primary_key",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500006,
		Name:          "proto2mysql.auto_increment_key",
		Tag:           "bytes,500006,opt,name=auto_increment_key",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500011,
		Name:          "proto2mysql.index",
		Tag:           "bytes,500011,opt,name=index",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500012,
		Name:          "proto2mysql.unique_key",
		Tag:           "bytes,500012,opt,name=unique_key",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         500021,
		Name:          "proto2mysql.tidb_nonclustered_pk",
		Tag:           "varint,500021,opt,name=tidb_nonclustered_pk",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         500022,
		Name:          "proto2mysql.tidb_shard_row_id_bits",
		Tag:           "varint,500022,opt,name=tidb_shard_row_id_bits",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         500023,
		Name:          "proto2mysql.tidb_pre_split_regions",
		Tag:           "varint,500023,opt,name=tidb_pre_split_regions",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         500024,
		Name:          "proto2mysql.tidb_auto_id_cache_one",
		Tag:           "varint,500024,opt,name=tidb_auto_id_cache_one",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600100,
		Name:          "proto2mysql.nullable",
		Tag:           "varint,600100,opt,name=nullable",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         600101,
		Name:          "proto2mysql.max_length",
		Tag:           "varint,600101,opt,name=max_length",
		Filename:      "proto2mysql_option.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// 标记本 .proto 文件用于 proto2mysql 建表，纯用途声明。
	// 注意：是否建表只取决于各 message 是否声明了 table_name；本选项不影响建表行为。
	//
	// optional bool db = 500000;
	E_Db = &file_proto2mysql_option_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// 表名（必填：声明了才视为一张表）
	//
	// optional string table_name = 500001;
	E_TableName = &file_proto2mysql_option_proto_extTypes[1]
	// 主键，逗号分隔 = 联合主键，如 "user_id,provider"
	//
	// optional string primary_key = 500002;
	E_PrimaryKey = &file_proto2mysql_option_proto_extTypes[2]
	// 自增字段名
	//
	// optional string auto_increment_key = 500006;
	E_AutoIncrementKey = &file_proto2mysql_option_proto_extTypes[3]
	// 普通索引：分号分隔多个索引，每个索引内逗号分隔 = 联合索引
	// 如 "player_id;zone_id,created_at"
	//
	// optional string index = 500011;
	E_Index = &file_proto2mysql_option_proto_extTypes[4]
	// 唯一键，逗号分隔 = 联合唯一键，如 "provider,provider_id"
	//
	// optional string unique_key = 500012;
	E_UniqueKey = &file_proto2mysql_option_proto_extTypes[5]
	// 主键追加 /*T![clustered_index] NONCLUSTERED */。
	// 业务自赋值的单调主键（如 Snowflake，时间戳在高位）在 TiDB 默认聚簇表下是
	// 官方点名的写热点场景；须配合 tidb_shard_row_id_bits 打散行分布。
	// 代价：主键点查多一次索引回表。
	//
	// optional bool tidb_nonclustered_pk = 500021;
	E_TidbNonclusteredPk = &file_proto2mysql_option_proto_extTypes[6]
	// 追加 /*T! SHARD_ROW_ID_BITS=N */，按 _tidb_rowid 打散写入。
	// 仅对非聚簇主键/无主键表生效：表有主键却未声明 tidb_nonclustered_pk 时，
	// 本选项被忽略并打日志告警（TiDB 聚簇表不支持，生成了也必然建表失败）。
	// 建议取 log2(TiKV 节点数) 数量级。
	//
	// optional uint32 tidb_shard_row_id_bits = 500022;
	E_TidbShardRowIdBits = &file_proto2mysql_option_proto_extTypes[7]
	// 与 SHARD_ROW_ID_BITS 同一注释块内追加 PRE_SPLIT_REGIONS=N（建表即预切 region）。
	// 依赖 tidb_shard_row_id_bits 存在，未声明时本选项被忽略；
	// TiDB 要求 N ≤ SHARD_ROW_ID_BITS，超出时收敛到 shard 值并打日志告警。
	//
	// optional uint32 tidb_pre_split_regions = 500023;
	E_TidbPreSplitRegions = &file_proto2mysql_option_proto_extTypes[8]
	// 表尾追加 /*T![auto_id_cache] AUTO_ID_CACHE=1 */：自增 ID 走集中分配（v6.4+），
	// 近似连续、仅 failover 出现小间隙。用于依赖自增连续性的表；默认按批缓存（3 万/批，重启跳号）。
	//
	// optional bool tidb_auto_id_cache_one = 500024;
	E_TidbAutoIdCacheOne = &file_proto2mysql_option_proto_extTypes[9]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// 该字段对应的列允许为 NULL（默认 NOT NULL）
	//
	// optional bool nullable = 600100;
	E_Nullable = &file_proto2mysql_option_proto_extTypes[10]
	// 主键/唯一键里 string/bytes 字段的最大长度，决定整列索引的列宽：
	//
	//	string → VARCHAR(N) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin，N 按字符计，取值 1..768；
	//	bytes  → VARBINARY(N)，N 按字节计，取值 1..3072。
	//
	// 不声明时 N = 191。目前仅用于主键/唯一键的 string/bytes 字段，声明在其它字段上（含显式写 0）会被拒绝。
	// 字节预算：单个索引（主键、唯一键、每个普通索引各自计算）所有列合计不得超过 3072 字节（InnoDB
	// 超出报 Error 1071）。VARCHAR(N) 按 4N 计、VARBINARY(N) 按 N 计；int32/uint32/enum/float 计 4，
	// int64/uint64/double/Timestamp 计 8，bool 计 1；普通索引里的非键 string/bytes 走 191 前缀，分别计 764/191。
	// 写入前按 N 校验，超长或非法 UTF-8 返回 ErrInvalidKeyValue，不会截断。
	//
	// optional uint32 max_length = 600101;
	E_MaxLength = &file_proto2mysql_option_proto_extTypes[11]
)

var File_proto2mysql_option_proto protoreflect.FileDescriptor

const file_proto2mysql_option_proto_rawDesc = "" +
	"\n" +
	"\x18proto2mysql_option.proto\x12\vproto2mysql\x1a google/protobuf/descriptor.proto:1\n" +
	"\x02db\x12\x1c.google.protobuf.FileOptions\x18\xa0\xc2\x1e \x01(\bR\x02db\x88\x01\x01:C\n" +
	"\n" +
	"table_name\x12\x1f.google.protobuf.MessageOptions\x18\xa1\xc2\x1e \x01(\tR\ttableName\x88\x01\x01:E\n" +
	"\vprimary_key\x12\x1f.google.protobuf.MessageOptions\x18\xa2\xc2\x1e \x01(\tR\n" +
	"primaryKey\x88\x01\x01:R\n" +
	"\x12auto_increment_key\x12\x1f.google.protobuf.MessageOptions\x18\xa6\xc2\x1e \x01(\tR\x10autoIncrementKey\x88\x01\x01::\n" +
	"\x05index\x12\x1f.google.protobuf.MessageOptions\x18\xab\xc2\x1e \x01(\tR\x05index\x88\x01\x01:C\n" +
	"\n" +
	"unique_key\x12\x1f.google.protobuf.MessageOptions\x18\xac\xc2\x1e \x01(\tR\tuniqueKey\x88\x01\x01:V\n" +
	"\x14tidb_nonclustered_pk\x12\x1f.google.protobuf.MessageOptions\x18\xb5\xc2\x1e \x01(\bR\x12tidbNonclusteredPk\x88\x01\x01:X\n" +
	"\x16tidb_shard_row_id_bits\x12\x1f.google.protobuf.MessageOptions\x18\xb6\xc2\x1e \x01(\rR\x12tidbShardRowIdBits\x88\x01\x01:Y\n" +
	"\x16tidb_pre_split_regions\x12\x1f.google.protobuf.MessageOptions\x18\xb7\xc2\x1e \x01(\rR\x13tidbPreSplitRegions\x88\x01\x01:X\n" +
	"\x16tidb_auto_id_cache_one\x12\x1f.google.protobuf.MessageOptions\x18\xb8\xc2\x1e \x01(\bR\x12tidbAutoIdCacheOne\x88\x01\x01:>\n" +
	"\bnullable\x12\x1d.google.protobuf.FieldOptions\x18\xa4\xd0$ \x01(\bR\bnullable\x88\x01\x01:A\n" +
	"\n" +
	"max_length\x12\x1d.google.protobuf.FieldOptions\x18\xa5\xd0$ \x01(\rR\tmaxLength\x88\x01\x01B.Z,github.com/luyuancpp/proto2mysql/pbopt;pboptb\x06proto3"

var file_proto2mysql_option_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil),    // 0: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
}
var file_proto2mysql_option_proto_depIdxs = []int32{
	0,  // 0: proto2mysql.db:extendee -> google.protobuf.FileOptions
	1,  // 1: proto2mysql.table_name:extendee -> google.protobuf.MessageOptions
	1,  // 2: proto2mysql.primary_key:extendee -> google.protobuf.MessageOptions
	1,  // 3: proto2mysql.auto_increment_key:extendee -> google.protobuf.MessageOptions
	1,  // 4: proto2mysql.index:extendee -> google.protobuf.MessageOptions
	1,  // 5: proto2mysql.unique_key:extendee -> google.protobuf.MessageOptions
	1,  // 6: proto2mysql.tidb_nonclustered_pk:extendee -> google.protobuf.MessageOptions
	1,  // 7: proto2mysql.tidb_shard_row_id_bits:extendee -> google.protobuf.MessageOptions
	1,  // 8: proto2mysql.tidb_pre_split_regions:extendee -> google.protobuf.MessageOptions
	1,  // 9: proto2mysql.tidb_auto_id_cache_one:extendee -> google.protobuf.MessageOptions
	2,  // 10: proto2mysql.nullable:extendee -> google.protobuf.FieldOptions
	2,  // 11: proto2mysql.max_length:extendee -> google.protobuf.FieldOptions
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	0,  // [0:12] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto2mysql_option_proto_init() }
func file_proto2mysql_option_proto_init() {
	if File_proto2mysql_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto2mysql_option_proto_rawDesc), len(file_proto2mysql_option_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 12,
			NumServices:   0,
		},
		GoTypes:           file_proto2mysql_option_proto_goTypes,
		DependencyIndexes: file_proto2mysql_option_proto_depIdxs,
		ExtensionInfos:    file_proto2mysql_option_proto_extTypes,
	}.Build()
	File_proto2mysql_option_proto = out.File
	file_proto2mysql_option_proto_goTypes = nil
	file_proto2mysql_option_proto_depIdxs = nil
}
